apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-registration-token
  namespace: {{ include "names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  token: "{{ required "Use --set release.registrationToken=<value> to define the Digital.ai Release registration token" .Values.release.registrationToken }}"
---
{{- if .Values.runner.truststore}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-truststore
  namespace: {{ include "names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  truststore.p12: {{ .Values.runner.truststore }}
  password: {{ .Values.runner.truststorePassword | b64enc }}
{{- end }}
