{{- if .Values.persistence.enabled }}
{{- $replicas := until (.Values.replicaCount | int) }}
{{- $persistence := .Values.persistence -}}
{{- $global := .Values.global -}}
{{- range $index := $replicas -}}
{{- if or $global.persistence.createVolume $persistence.work.volume.create }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-runner-work-{{ include "common.names.fullname" . }}-{{ $index }}
  namespace: {{ include "names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{ include "common.storage.class" (dict "persistence" .Values.persistence.work.storageClass "global" .Values.global.persistence) }}
  capacity:
    storage: {{ $persistence.work.volume.size }}
  accessModes:
    {{- range  $persistence.work.accessModes }}
    - {{ . | quote }}
    {{- end }}
  hostPath:
    path: "{{ required "Use --set persistence.work.volume.baseHostPath=<value> or --set global.persistence.baseHostPath=<value> to define remote-runner host path" (default $global.persistence.baseHostPath $persistence.work.volume.baseHostPath) }}/work"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: job-runner-work-{{ include "common.names.fullname" . }}-{{ $index }}
    namespace: {{ include "names.namespace" . | quote }}
{{- end }}
{{- if or $global.persistence.createVolume $persistence.db.volume.create }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-runner-db-{{ include "common.names.fullname" . }}-{{ $index }}
  namespace: {{ include "names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{ include "common.storage.class" (dict "persistence" .Values.persistence.db.storageClass "global" .Values.global.persistence) }}
  capacity:
    storage: {{ $persistence.db.volume.size }}
  accessModes:
    {{- range .Values.persistence.db.accessModes }}
    - {{ . | quote }}
    {{- end }}
  hostPath:
    path: "{{ required "Use --set persistence.db.volume.baseHostPath=<value> or --set global.persistence.baseHostPath=<value> to define remote-runner host path" (default $global.persistence.baseHostPath $persistence.db.volume.baseHostPath) }}/db"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: job-runner-db-{{ include "common.names.fullname" . }}-{{ $index }}
    namespace: {{ include "names.namespace" . | quote }}
{{- end }}
{{- end }}
{{- end }}
