name: Publish Helm Chart (Github)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v3
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Helm Repository Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          ref: master
      - name: Helm Package (GCR)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/remote-runner
        run: |
          CHART_VERSION=$(helm show chart . | grep "^version:" | awk '$1 { print $2 }')
          CHART_PACKAGE_NAME="remote-runner-$CHART_VERSION"
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm dependency update
          helm package . --version "$CHART_VERSION" -d helm
          helm repo index .
          echo ${{ env.GITHUB_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin
          helm push helm/remote-runner-$CHART_VERSION.tgz ${{ env.GCR_IMAGE }}:${{ github.sha }}
